LOCAL_PATH := $(call my-dir)

FUJISAN_HWC_MODULE := hwcomposer.$(TARGET_BOARD_PLATFORM)

include $(CLEAR_VARS)
LOCAL_MODULE := fujisan_hwcomposer_vendor_64
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 64
LOCAL_INSTALLED_MODULE_STEM := $(FUJISAN_HWC_MODULE).so
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/hw
LOCAL_REQUIRED_MODULES := $(FUJISAN_HWC_MODULE)
LOCAL_PREBUILT_MODULE_FILE := \
    $(call intermediates-dir-for,SHARED_LIBRARIES,$(FUJISAN_HWC_MODULE))/$(FUJISAN_HWC_MODULE).so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fujisan_hwcomposer_vendor_32
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 32
LOCAL_INSTALLED_MODULE_STEM := $(FUJISAN_HWC_MODULE).so
LOCAL_MODULE_PATH := $($(TARGET_2ND_ARCH_VAR_PREFIX)TARGET_OUT_VENDOR_SHARED_LIBRARIES)/hw
LOCAL_REQUIRED_MODULES := $(FUJISAN_HWC_MODULE)
LOCAL_PREBUILT_MODULE_FILE := \
    $(call intermediates-dir-for,SHARED_LIBRARIES,$(FUJISAN_HWC_MODULE),,,1)/$(FUJISAN_HWC_MODULE).so
include $(BUILD_PREBUILT)
